# Generated by Django 5.1.2 on 2025-04-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="products/")),
                ("model", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Car", "Car"),
                            ("Bike", "Bike"),
                            ("Inverter", "Inverter"),
                        ],
                        max_length=100,
                    ),
                ),
                ("capacity", models.CharField(max_length=50)),
                ("warranty", models.CharField(max_length=100)),
                ("mrp", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "with_old_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "without_old_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=100)),
                ("note", models.TextField(blank=True)),
                ("description", models.TextField()),
                ("recommended_for", models.TextField(blank=True)),
                ("is_best_seller", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="store.product",
                    ),
                ),
            ],
        ),
    ]
