# Generated by Django 5.1.2 on 2025-04-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
