# Generated by Django 5.1.2 on 2025-04-18 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="with_old_price",
            new_name="price_with_old_battery",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="without_old_price",
            new_name="price_without_old_battery",
        ),
    ]
