# Generated by Django 5.1.2 on 2025-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="carbrand",
            name="category",
            field=models.CharField(
                choices=[
                    ("2_wheeler", "2 Wheeler Batteries"),
                    ("Car", "Car"),
                    ("computer_ups", "Computer UPS"),
                    ("inverter_combo", "Inverter and Battery Combo"),
                    ("inverter_ups", "Inverter and UPS Systems"),
                    ("inverter_batteries", "Inverter Batteries"),
                    ("smf_vrla", "SMF/VRLA Batteries"),
                    ("truck", "Truck Batteries"),
                    ("lithium_ion", "Lithium Ion Batteries"),
                    ("inverter_lithium", "Inverter + Lithium Ion Batteries"),
                ],
                default="Car",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("2_wheeler", "2 Wheeler Batteries"),
                    ("Car", "Car"),
                    ("computer_ups", "Computer UPS"),
                    ("inverter_combo", "Inverter and Battery Combo"),
                    ("inverter_ups", "Inverter and UPS Systems"),
                    ("inverter_batteries", "Inverter Batteries"),
                    ("smf_vrla", "SMF/VRLA Batteries"),
                    ("truck", "Truck Batteries"),
                    ("lithium_ion", "Lithium Ion Batteries"),
                    ("inverter_lithium", "Inverter + Lithium Ion Batteries"),
                ],
                max_length=100,
            ),
        ),
    ]
