# Generated by Django 5.1.2 on 2025-06-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_carbrand_category_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_with_old_battery",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="price_without_old_battery",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="warranty",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
